blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/Jalez/TDDProject/issues/new?template=bug_report.md
    about: File a bug report to help us improve our project.
  - name: Feature Request
    url: https://github.com/Jalez/TDDProject/issues/new?template=feature_request.md
    about: Suggest a new feature or improvement.
