name: Run JavaScript Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and submodules
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive   # This will initialize and update submodules recursively
          fetch-depth: 0           # Ensures the full history is fetched (required for submodules)

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run tests
        run: npm test
